name: wechaty-meme-bot-pypi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r frontend/requirements.txt

    - name: Install Pushing & Packing dependencies
      run: |
        pip install -r frontend/requirements-dev.txt
        pip install setuptools wheel twine

    - name: Pack
      run: make dist

    - name: Check if publish this branch
      id: check-branch
      run: |
        if [[ ${{ github.ref }} =~ ^refs/heads/(master|v[0-9]+\.[0-9]+.*)$ ]]; then
            echo ::set-output name=match::true
        fi  # See: https://stackoverflow.com/a/58869470/1123955

    - name: Publish Branch
      if: github.event_name == 'push' && steps.check-branch.outputs.match == 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run:
        cd frontend && python3 -m twine upload --skip-existing dist/*