# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python-meme-bot-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        model-gdrive-id: [17m3FkOl2CS79env_JdO11vzuGzLYRoA3]
        model-zip-name: [meme-bot-models.zip]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r frontend/requirements.txt
        pip install -r backend/requirements.txt

    - name: Download Models from Google Drive & Unzip them
      run: |
        curl gdrive.sh | bash -s ${{ matrix.model-gdrive-id }}
        unzip ${{ matrix.model-zip-name }} ./backend

    - name: Test
      run: make test
